[{${key}}-DlgOrder]
Dlg0={${key}}-LicenseCustom-0
Count=4
Dlg1={${key}}-AskYesNo-0
Dlg2={${key}}-SdComponentDialogAdv-0
Dlg3={${key}}-SdFinishReboot-0
[{${key}}-LicenseCustom-0]
Result=1
[{${key}}-SdComponentDialogAdv-0]
szDir=${path}
Result=1
[{${key}}-SdFinishReboot-0]
Result=1
BootOption=0
[{${key}}-AskYesNo-0]
Result=1
